Require Export GHC.Base.
Require Export GHC.List.
Require Export GHC.Enum.
Require Export GHC.Real.
Require Export GHC.Unicode.
Require Export Data.Tuple.
Require Export Data.Maybe.
Require Export Data.Bool.
Require Export Data.Function.